### ISSUE TITLE
Save Prediction in GeoTIFF Format and Generate Geojson

### ISSUE THREAD

**Issue by Ehsan125** [SpaceNetChallenge/SpaceNet_SAR_Buildings_Solutions#5]
I am running the `test_spacenet6.ipynb`

Can i save the predicted output images in the .GeoTIFF, so that we can generate the geojson of the detected buildings? Actually i want the geojson of the predicted masks of the buildings. 
Thank you

**Comment by motokimura** [comment]
You need to find out how to do that by yourself since that kind of conversion is not required in this competition.

**Comment by Ehsan125** [comment]
> You need to find out how to do that by yourself since that kind of conversion is not required in this competition.

No problem, I will try to do it by myself. thank you for your reply i am closing this issue, Moreover, if you can provide help on other issue i.e. `Convert mask to polygons` It would be highly appreciated.
